### ISSUE TITLE
مطالب پیشرفته

### ISSUE THREAD

**Issue by MetaiR** [saeiddrv/PythonPersianTutorial#2]
سلام
ایا امکان توضیح درباره مطالب پیشرفته مثل برخی ماژول ها(مثلا سیس یا مولتی پروسسور) هست؟

**Comment by saeiddrv** [comment]
سلام
بله حتما؛ اتفاقن تو همین درس بعدی قرار گذاشتم چندتاشون رو بنویسیم

**Comment by MetaiR** [comment]
@saeiddrv 
آیا کمکی از دست بنده بر میاد؟ من به تازگی مدرک در زمینه پایتون گرفتم نمیدونم برای شما معتبر هست یا خیر
![cert-1073-567685](https://cloud.githubusercontent.com/assets/7807264/13548204/03b96e46-e300-11e5-85dd-f2b2c979dd2a.jpg)

**Comment by saeiddrv** [comment]
واوووو
حتما؛ هر جایی رو که تشخیص دادین نیاز به اصلاح و تکمیل داره
من استقبال می‌کنم... یا حتی مطلب جدید...
ممنون

**Comment by MetaiR** [comment]
ان شالله بتونم کمکی کنم

**Comment by AmirHejazi** [comment]
@saeiddrv @MetaiR 
سلان دوستان خسته نباشید. من به تازگی قصد  دارم برنامه نویسی اندروید رو شروع کنم. از طرفی هم امکانات پایتون برام جذابه
توی مدرسه و دانشگاه یک کم، بیسیک، پاسکال، سی و متلب کار کردم. 
سوالم اینه پایتون برای اندروید هم به کار میاد و بهینه هست. یا یاد گرفتن پایتون برای نوشتن برنامه های اندروید وقت تلف کردنه. برای اندروید از کجا شروع کنم. 
این لینک رو دیده ام
https://python-for-android.readthedocs.org/en/latest/
چیز به درد بخوری توش هست؟
ممنون

**Comment by MetaiR** [comment]
@AmirHejazi 
سلام دوست عزیز
در ابتدا باید به این مسله اشاره کنم ک اندروید نوعی لینوکس هست و این مسله به این معنیه ک پایتون به صورت اماده درش وجود داره
از طرفیم پایتون دارای ماژول ها و فریم ورک های زیادی برای اندروید هست ک از جمله ی اونا میشه به "اس ال 4 ای" به عنوان ماژول و فریم ورک کیوی اشاره کرد.
مسله مهمی ک در اینجا وجود داره اینه ک متاسفانه در کشور ما اکثرا به چیز هایی ک شنیدن اهمیت میدن
برای مثال وقتی من با همکارام در خصوص برنامه نویسی اندروید با پایتون صحبت میکنم متاسفانه به دلیل اینکه در گذشته شنیدن ک با جاوا نوشته میشه متوجه حرف بنده نمیشن و این در حالیه ک برنامه ای ک با پایتون برای اندروید میشه نوشت همه جور امکانی میتونه داشته باشه حتی با فریم ورک کیوی میشه فایل اِی پی کی هم ایجاد کرد.
امیدوارم این صحبت کمکی کرده باشه به شما
اگر میخواین نمونه کوچکی از برنامه های اندروید نوشته شده با پایتون رو ببینین برنامه ی زیر رو روی گوشی نصب و از بخش پروگرمز نمونه برنامه ها رو ببینین البته این مثال خیلی کوچکی هست
QPython3

**Comment by saman-karvandi** [comment]
با سلام.
من سالها کارم لینوکس، شل اسکریپت و اوراکل بود.
از تقریبا شش ماه پیش یک دوره آموزشی با edX شروع کردم و با نمره ۱۰۰ از ۱۰۰ سرتیفیکیت گرفتم و از آن موقع تفریحی در منزل کدهای کوچک می نویسم.
الآن می خواهم این کار را جدی شروع کنم. نمی دانم با پلتفورم وب کار کنم یا راسب بری یا ... ممکنه من را راهنمایی کنید و برای آن راهنمای آموزشی بدید و بفرمایید چه باید بکنم؟
ممنون.

**Comment by saeiddrv** [comment]
سلام @AmirHejazi عزیز
:) البته که با پایتون وقت کسی هدر نمیشه
ولی از اونجایی که بحث کارایی هم اینجا مطرح میشه و منم با اندروید غریبه‌ام
چیزی نمیتونم بگم...

@sajadshokri  کمک :)

**Comment by MetaiR** [comment]
@saman-karvandi 
با سلام
دوست عزیز اول از همه به شما تبریک میگم ک با نمره 100 از 100 گواهی گرفتین اما در کنار این تبریک باید بگم تجربه کاری و اکادمیک دو چیز کامل جدا از هم هست
باور خود من این هست ک با تقریبا هر زبونی شما میتونید هر چیزی بنویسید چ وب چ دسکتاپ و غیره ولی مسلما هر زبون برای یک سری کار مناسب تر هست.
چیزی ک هست اینه ک اگر شما یک زبان سی لایک رو یاد بگیرید به دلیل شباهت سینتکسی راحت میتونید زبون های دیگه رو هم طی مدت بسیار کوتاهی یاد بگیرید.
من خودم زبون های جاوا سی پلاس پلاس پایتون پی اچ پی جاوا اسکریپت رو مطالعه کردم اما در بین همه ی اونا از پی اچ پی برای وب استفاده میکنم و از پایتون برای غیر وب (البته با پایتون هم میشه وب اپلیکیشن ساخت ولی به شخصه با پی اچ پی برای وب راحت ترم

**Comment by saman-karvandi** [comment]
درست می فرمایید. بنده راستش علاقه زیادی به کار روی وب ندارم و بیشتر برایم راسب بری و امبدد و یا اپ های روی سیستم هیجان انگیز است و علاقه مند. برای ادامه کار در این زمینه ممکنه من را راهنمیی کنید؟ از نظر آموزش و شروع کار.
پیشنهاد می کنید برای ادامه چه زبانی را شروع کنم؟
ممنون.

**Comment by MetaiR** [comment]
@saman-karvandi 
راستشو بخواین اولیت اصلی با علاقه س
ولی اگر خودم باشم بیشتر سمت زبون های های لول و اسکریپتی مخصوصا پایتون میرم اما اگر سر و کارم با بیگ دیتا های خیلی خیلی بزرگ بخوره میرم سمت یه چیز سبک و خالص و کوچیک مثل سی پلاس پلاس
البته پایتون ک من باهاش کار کردم هم برای بیگ دیتا در حد گشت و گذار تک تک 400000 دیتا توی 3.5 میلیون دیتا و اتچ کردن اطلاعات بهشون خوب نتیجه داد
تقریبا 4 ساعت البته بگم ک از مولتی پروسسور استفاده نکردم و الا فکر کنم توی 1 ساعت یا خیلی کمتر جواب میداد
از طرفیم پایتون خیلی از سینتکس های اذیت کننده زبون های دیگه رو نداره برای همین برای شروع پایتون رو ما معمولا پیشنهاد میدیم
البته وقتی یکم جهانی نگاه کنیم و نمونه شرکت هایی ک از پایتون استفاده میکنن رو ببینیم هم میتونیم بگیم ک پایتون انتخاب مناسبیه
سه تا از این مثال ها ک از پایتون استفاده کردن و میکنن:
گوگل ، سی آی ای ، ناسا
فک کنم همینا بس باشه :)

**Comment by saman-karvandi** [comment]
ممنون. هم نظر هستیم تا اینجای کار :)
من دوره پایتون پروگرمینگ در ای دی ایکس دیم که شامل آموزش پایتون ۲ و ۳ هست. برای ادامه در پایتون چه آموزشی را پیشنهاد می دید. برای امبدد هم با پایتون آموزشی مدنظر دارید؟ البته به غیر است کتاب راسب بری سیمون مونک.
متشکرم.

**Comment by MetaiR** [comment]
@saman-karvandi 
ببینید اصل یاد گیری یه زبان برنامه نویسی یکی هست حالا هر چنتا هم کتاب بخونید در نهایت همشون یه چیز بهتون یاد میدن و مهم همون اصول اولیه هست و بقیه ش همه به مهارت های ذهنی و الگریتمی شما مربوط میشه پس اینکه چه کتاب یا چ دوره ای رو بخونم از نظر من خیلی مهم نیست و اگر پیشنهاد منو میخواین در صورتی ک اینگیلیستون خوبه یه سر به سایت زیر بزنین و اگرم خوب نیست همین کتابی ک دوستمون در گیت هاب تهیه و گذاشتن مناسب هست اینطوری هم با مفاهیم پایه آشنایی پیدا میکنین هم اگر خواستین چیز بیشتری بدونین اونوقت میتونین با دقت خیلی بیشتر و اساسی تر پول رو خرج و صرف این کار کنین در ضمن میتونین ببینید با پایتون ارتباط برقرار میکنین یا نه
در خصوص پایتون 2 یا 3
باید بگم ک پایتون 3 و 2 از نظر سینتکسی باهم فرق دارند و البته چون تیم دولوپ پایتون تضمین دادن ک نسخه های اینده فقط از سینتکس ورژن 3 استفاده میکنن پس بهتره نسخه ی 3 رو آموزش ببینید و هنگام نصب پیشنهاد من 3.4 هست چون اکثر ماژول ها براش موجوده
سایتی که گفته بودم : sololearn.com

**Comment by MetaiR** [comment]
دوستان لطفا برای مباحث جدید ایشو ی جدید باز کنید و همه رو در اینجا وارد نکنین تا بقیه هم ک مشکلات شما رو داشتن بتونن راحت تر به نتیجه برسن

**Comment by saman-karvandi** [comment]
بسیار ممنونم. تا الآن همه این کارهایی رو که گفتید کرده ام و پایتونی که کار می کنم هم ۳.۴ هست. پس می رم دنبال اینکه بیشتر کد بنویسم و چون امبدد دوست دام، روی آن فوکوس کنم.
ممنون.

**Comment by MetaiR** [comment]
@saman-karvandi 
خواهش میکنم
البته منظورتون از امبدد اگر تعریف زیر هست:
"یک سیستم تعبیه شده متشکل از سخت‌افزار و نرم‌افزار و وسایل مکانیکی اضافه شده است که برای عملیاتی مشخص تعبیه شده باشد."
باید بگم ک خودم تا حالا دنبالش نبودم اما چون یکی از کاربرد های پایتون هوش مصنوعی هست و میشه گفت ربات و رباتیک یک نوع امبدد هستن (طبق تعریف بالا اگر اشتباه نکنم) پس احتمال خیلی قوی میشه
بنده خودم  وی این زمینه فقط در حد پردازش تصویر برای سیستم های امبدد رفتم جلو
البته اگر منظور و مقصود شما از امبدد تعریف بالا نباشه خوشحال میشم به ما هم منظور رو بگین و یه چیزی یاد بیگریم :)

**Comment by saman-karvandi** [comment]
من سه تا لینک زیر را برای روشنایی بیشتر موضوع قرار می دهم.

https://wiki.python.org/moin/EmbeddedPython
http://www.embedded.com/
https://en.wikipedia.org/wiki/Embedded_system

**Comment by MetaiR** [comment]
خب لینک سوم تعریف بنده هست دیگه :)

**Comment by saman-karvandi** [comment]
درسته. یکی از کاربردها این است. میکروکنترلر پروگرمینگ که بر پایه امبدد سیستم هست در اروپا و آمریکا بیشترین بازار کار را دارد. از چراغ راهنمایی یا تابلوی مترو بگیرید تا روبات و جنگنده و ... همگی نیاز به امبدد پروگرمینگ دارند. برای همین من سهتا لینک دادم که اطلاعات کامل برای همه کاملتر شود.
ممنون و موفق باشید.

**Comment by aliyarali** [comment]
سلام دوستان.یه سوال داشتم
برای ساخت بازی پای گیم رو امتحان کردم اما حس کردم از نظر قدرت گرافیکی و سرعت زیاد دلچسب نیست.برای بازی سازی به خصوص برای اندروید چه زبانی بهتره؟
