### ISSUE TITLE
More about OOP

### ISSUE THREAD

**Issue by aryanbadiee** [saeiddrv/PythonPersianTutorial#3]
for general users:
The following is in persian (pinglish)

salam
man mikhastam be yeki az dustam site farsi amuzesh python moarefi konm (chon be zaban english mosalat nist ke betune document haye [python.org](https://www.python.org) ro bekhune) ke site shomaro didam.
vaghean site khubi darin va mataleb ro dar hadi ke man didam sade va ba mesal kafi avordin
va masalee ke shakhsan kheili azash lezat bordam hamin open source budan va link be source haye original bud ke tuye kheili az amuzesh haye farsi chenin chizi nist motoasefane!
be hamin dalil khastam be amuzesh haye site shoma komak konm, dar surati ke shoma ok bashin

**OOP**:
OOP dar python yeki az asli tarin ravesh ha vase barnamenevisi
dar site shoma matlab haye koli rajebesh gofte shode vali hes mikonm mishe yeseri mataleb dg ham behesh ezafe beshe az jomle:
* inheritance & multi-inheritance
* operators overloading
* Python Encapsulation  (e.g. : `self.__variable`)

ke in mataleb nokate asli tu OOP barnamenevisi kardane
age mayel bashin mitunam ba fork karan tu neveshtan in mataleb komak konm.

sepas babate site khubetun.

**Comment by sajadshokri** [comment]
Hello Aryan and thank you for showing interest.
This Book is open source so everyone can edit and add new pages to it. Feel free to write as much as you like and we appreciate that. 
Please follow [GitHub Flow](https://guides.github.com/introduction/flow/) ;

سلام آریان، ممنون که به این کتاب علاقه نشون دادی.
این کتاب متن باز است و هرکسی میتونه اون رو تغییر بده یا مطلبی اضافه کنه، این باعث خوشحالی ما خواهد بود و پیشاپیش قدردانی میکنیم.
لطفا  [روند گیتهاب](https://guides.github.com/introduction/flow/)  را دنبال کنید.

**Comment by aryanbadiee** [comment]
you're welcome.
i will add contents and send pull requests

خواهش میکنم
من بزودی مطالب را آماده کرده و برای شما ارسال میکنم
