### ISSUE TITLE
Request pdf version

### ISSUE THREAD

**Issue by KomeilParseh** [saeiddrv/PythonPersianTutorial#43]
# Request pdf version

Hello, if possible, please provide a **pdf** and **epub** version. Thanks

**Comment by saeiddrv** [comment]
Hi Komeil,
Unfortunately, Sphinx framework does not support Persian language to create pdf/epub formats.
But I'm planning to create a separate electronic version. Anyway, the current version is completely free, and if someone prepares other formats of it, I will link it in the current version if it matches completely.

Thankful

**Comment by KomeilParseh** [comment]
Hi Saeiddrv

Thanks for the reply I want to convert rust to PDF (with **a python library**  and **GitHub Action**)
My question was, should I apply for traction here or elsewhere?
