### ISSUE TITLE
کتاب پایتون

### ISSUE THREAD

**Issue by musicsd** [saeiddrv/PythonPersianTutorial#7]
درود
سپاس بی‌کران از مهر و دانش پراکنیدن شما. خواهشمندم اگر شدنی‌ست این برنامه را ادامه دهید.

**Comment by saeiddrv** [comment]
@musicsd  سلام، ممنون، کتاب رها نشده و درحال توسعه است منتها با سرعت خیلی کم به خاطر مشکلات زمانی. سعی میکنم سرعت کار افزایش پیدا کنه.
